name: Ruby

on:
  push:
    branches:
      - master
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Install Bundler
        run: |
          set -e
          gem install bundler
          bundle install
      - name: Jekyll Build
        run: |
          set -e
          bundle exec jekyll build
      - name: Build Gem file
        run: |
          set -e
          if test -e "./gphome/index.html";then
            echo "It builds!"
          else
            echo "Huh. That's odd. The example site doesn't seem to build."
            exit 1
          fi
      - name: Deploy action for GitHub Pages
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./gphome

